### ISSUE TITLE
切片的时候疑似会丢失踏板或者其它控制信息

### ISSUE THREAD

**Issue by heeeycu** [FlyToYourMooN/DDPM-Midi2Performance-Model#4]
有趣的小工具！
但是我发现踏板效果随着切片可能会时有时无，我看了一下代码部分，切片的时候好像没有考虑midi的控制信息不是帧/note级别，感觉需要在这里特殊处理一下，让控制信息不受切片影响。

**Comment by FlyToYourMooN** [comment]
是的，我仅考虑了使用的两个数据集，还需要写一个处理用户自己MIDI的脚本
